### ISSUE TITLE
Error 500 internal server error - NoMethodError

### ISSUE THREAD

**Issue by jforeman** [Contargo/redmine_oidc#12]
Hey there,

We're just setting up redmine_oidc with Redmine 4.2.10 and Keycloak and seeing this error:
```
plugins/redmine_oidc/app/controllers/oidc_controller.rb:26:in `login'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
Started GET "/" for x.x.x.x at 2023-06-19 20:45:46 +0000
Processing by WelcomeController#index as HTML
  Current user: anonymous
  Rendering welcome/index.html.erb within layouts/base
  Rendered collection of news/_news.html.erb [5 times] (15.0ms)
  Rendered welcome/index.html.erb within layouts/base (26.1ms)
Completed 200 OK in 84ms (Views: 46.7ms | ActiveRecord: 21.2ms)
Started GET "/" for 10.3.82.4 at 2023-06-19 20:45:49 +0000
Processing by WelcomeController#index as HTML
  Current user: anonymous
  Rendering welcome/index.html.erb within layouts/base
  Rendered collection of news/_news.html.erb [5 times] (9.4ms)
  Rendered welcome/index.html.erb within layouts/base (13.6ms)
Completed 200 OK in 55ms (Views: 29.6ms | ActiveRecord: 10.2ms)
Started GET "/login" for 10.3.82.4 at 2023-06-19 20:45:51 +0000
Processing by AccountController#login as HTML
  Current user: anonymous
Redirected to http://x.x.x.x/oidc/login
Completed 302 Found in 7ms (ActiveRecord: 1.7ms)
Started GET "/oidc/login" for 10.3.82.4 at 2023-06-19 20:45:51 +0000
Processing by OidcController#login as HTML
  Current user: anonymous
Completed 500 Internal Server Error in 12ms (ActiveRecord: 1.3ms)

 

NoMethodError (undefined method `authorization_endpoint' for nil:NilClass):

 

plugins/redmine_oidc/app/models/oidc_session.rb:158:in `oidc_client'
plugins/redmine_oidc/app/models/oidc_session.rb:41:in `authorization_endpoint'
plugins/redmine_oidc/app/controllers/oidc_controller.rb:26:in `login'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
```

Any thoughts on how to proceed?

Thank you!

**Comment by jforeman** [comment]
I added some debug statements and found that the keycloak URL was incorrect. 
OIDC discovery failed: Failed to open TCP connection to localhost:7080 (Connection refused - connect(2) for "localhost" port 7080)
Completed 500 Internal Server Error in 16ms (ActiveRecord: 2.8ms)
